export const citiesByState = {
  'Andhra Pradesh': [
    'Amaravati',
    'Vijayawada',
    'Visakhapatnam',
    'Tirupati',
    'Guntur',
    'Nellore',
    'Kurnool',
    'Rajahmundry',
    'Kadapa',
    'Anantapur',
  ],
  'Arunachal Pradesh': [
    'Itanagar',
    'Naharlagun',
    'Pasighat',
    'Roing',
    'Tawang',
    'Bomdila',
    'Ziro',
    'Tezu',
    'Yingkiong',
    'Along',
  ],
  Assam: [
    'Guwahati',
    'Jorhat',
    'Silchar',
    'Dibrugarh',
    'Nagaon',
    'Tezpur',
    'Tinsukia',
    'Bongaigaon',
    'Goalpara',
    'Dhubri',
  ],
  Bihar: [
    'Patna',
    'Gaya',
    'Bhagalpur',
    'Muzaffarpur',
    'Darbhanga',
    'Purnia',
    'Ara',
    'Begusarai',
    'Katihar',
    'Munger',
  ],
  Chhattisgarh: [
    'Raipur',
    'Bilaspur',
    'Bhilai',
    'Korba',
    'Jagdalpur',
    'Raigarh',
    'Ambikapur',
    'Dhamtari',
    'Durg',
    'Rajnandgaon',
  ],
  Goa: [
    'Panaji',
    'Margao',
    'Vasco da Gama',
    'Mapusa',
    'Ponda',
    'Bicholim',
    'Sanquelim',
    'Curchorem',
    'Valpoi',
    'Canacona',
  ],
  Gujarat: [
    'Ahmedabad',
    'Surat',
    'Vadodara',
    'Rajkot',
    'Bhavnagar',
    'Jamnagar',
    'Junagadh',
    'Gandhinagar',
    'Nadiad',
    'Morbi',
  ],
  Haryana: [
    'Chandigarh',
    'Faridabad',
    'Gurugram',
    'Hisar',
    'Karnal',
    'Sonipat',
    'Panipat',
    'Ambala',
    'Yamunanagar',
    'Rohtak',
  ],
  'Himachal Pradesh': [
    'Shimla',
    'Solan',
    'Mandi',
    'Kangra',
    'Una',
    'Kullu',
    'Chamba',
    'Hamirpur',
    'Bilaspur',
    'Nahan',
  ],
  Jharkhand: [
    'Ranchi',
    'Jamshedpur',
    'Dhanbad',
    'Bokaro Steel City',
    'Deoghar',
    'Hazaribagh',
    'Giridih',
    'Ramgarh',
    'Medininagar',
    'Chirkunda',
  ],
  Karnataka: [
    'Bangalore',
    'Mysore',
    'Hubli-Dharwad',
    'Mangalore',
    'Gulbarga',
    'Belgaum',
    'Davangere',
    'Bellary',
    'Bijapur',
    'Shimoga',
  ],
  Kerala: [
    'Thiruvananthapuram',
    'Kochi',
    'Kozhikode',
    'Thrissur',
    'Kannur',
    'Kollam',
    'Palakkad',
    'Alappuzha',
    'Kasaragod',
    'Pathanamthitta',
  ],
  'Madhya Pradesh': [
    'Bhopal',
    'Indore',
    'Jabalpur',
    'Gwalior',
    'Ujjain',
    'Sagar',
    'Dewas',
    'Satna',
    'Ratlam',
    'Rewa',
  ],
  Maharashtra: [
    'Mumbai',
    'Pune',
    'Nagpur',
    'Thane',
    'Nashik',
    'Aurangabad',
    'Solapur',
    'Amravati',
    'Kolhapur',
    'Akola',
  ],
  Manipur: [
    'Imphal',
    'Thoubal',
    'Churachandpur',
    'Bishnupur',
    'Senapati',
    'Ukhrul',
    'Tamenglong',
    'Kakching',
    'Jiribam',
    'Kangpokpi',
  ],
  Meghalaya: [
    'Shillong',
    'Tura',
    'Jowai',
    'Nongpoh',
    'Williamnagar',
    'Baghmara',
    'Resubelpara',
    'Mairang',
    'Sohra',
    'Nongstoin',
  ],
  Mizoram: [
    'Aizawl',
    'Lunglei',
    'Champhai',
    'Serchhip',
    'Kolasib',
    'Lawngtlai',
    'Saiha',
    'Mamit',
    'Hnahthial',
    'Khawzawl',
  ],
  Nagaland: [
    'Dimapur',
    'Kohima',
    'Mokokchung',
    'Tuensang',
    'Wokha',
    'Zunheboto',
    'Phek',
    'Mon',
    'Kiphire',
    'Longleng',
  ],
  Odisha: [
    'Bhubaneswar',
    'Cuttack',
    'Rourkela',
    'Brahmapur',
    'Sambalpur',
    'Puri',
    'Balasore',
    'Bhadrak',
    'Baripada',
    'Jharsuguda',
  ],
  Punjab: [
    'Amritsar',
    'Ludhiana',
    'Patiala',
    'Jalandhar',
    'Bathinda',
    'Hoshiarpur',
    'Pathankot',
    'Moga',
    'Mohali',
    'Firozpur',
  ],
  Rajasthan: [
    'Jaipur',
    'Jodhpur',
    'Udaipur',
    'Kota',
    'Ajmer',
    'Bikaner',
    'Bhilwara',
    'Alwar',
    'Bharatpur',
    'Sri Ganganagar',
  ],
  Sikkim: [
    'Gangtok',
    'Namchi',
    'Gyalshing',
    'Mangan',
    'Jorethang',
    'Ravangla',
    'Rangpo',
    'Singtam',
    'Yuksom',
    'Soreng',
  ],
  'Tamil Nadu': [
    'Chennai',
    'Coimbatore',
    'Madurai',
    'Tiruchirappalli',
    'Tiruppur',
    'Salem',
    'Erode',
    'Tirunelveli',
    'Vellore',
    'Thoothukudi',
  ],
  Telangana: [
    'Hyderabad',
    'Warangal',
    'Nizamabad',
    'Karimnagar',
    'Khammam',
    'Ramagundam',
    'Mahbubnagar',
    'Nalgonda',
    'Adilabad',
    'Siddipet',
  ],
  Tripura: [
    'Agartala',
    'Udaipur',
    'Dharmanagar',
    'Kailashahar',
    'Kamalpur',
    'Ambassa',
    'Belonia',
    'Sonamura',
    'Bishalgarh',
    'Sabroom',
  ],
  'Uttar Pradesh': [
    'Lucknow',
    'Kanpur',
    'Agra',
    'Varanasi',
    'Allahabad',
    'Meerut',
    'Ghaziabad',
    'Bareilly',
    'Aligarh',
    'Moradabad',
  ],
  Uttarakhand: [
    'Dehradun',
    'Haridwar',
    'Haldwani',
    'Roorkee',
    'Rudrapur',
    'Kashipur',
    'Nainital',
    'Udham Singh Nagar',
    'Chamoli',
    'Pithoragarh',
  ],
  'West Bengal': [
    'Kolkata',
    'Asansol',
    'Siliguri',
    'Durgapur',
    'Bardhaman',
    'Malda',
    'Baharampur',
    'Habra',
    'Kharagpur',
    'Haldia',
  ],
}

export const religionsInIndia = [
  'Hinduism',
  'Islam',
  'Christianity',
  'Sikhism',
  'Buddhism',
  'Jainism',
  'Zoroastrianism',
  'Judaism',
  "Baha'i",
  'Sarnaism',
]

export const bloodGroups = ['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-']
